// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR6gleQybWxQ9mITjxpwVuL3Qaq5l8HpA',
    appId: '1:629488447603:web:2ecc6cf8ba966142133a06',
    messagingSenderId: '629488447603',
    projectId: 'zoomy-clone',
    authDomain: 'zoomy-clone.firebaseapp.com',
    storageBucket: 'zoomy-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApnal4tratNDKR0hAnfNHf9doRjrPha64',
    appId: '1:629488447603:android:abaa1d74579b385e133a06',
    messagingSenderId: '629488447603',
    projectId: 'zoomy-clone',
    storageBucket: 'zoomy-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCp_DLjTNC8Cv-avugR_t1nd-7_8aNuBM',
    appId: '1:629488447603:ios:5c35466d9f8303d7133a06',
    messagingSenderId: '629488447603',
    projectId: 'zoomy-clone',
    storageBucket: 'zoomy-clone.appspot.com',
    iosClientId: '629488447603-1e26ill2a3k8ev4lt8v9s8kd6bu83dql.apps.googleusercontent.com',
    iosBundleId: 'Maheresio.zoomyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCp_DLjTNC8Cv-avugR_t1nd-7_8aNuBM',
    appId: '1:629488447603:ios:6397cd0c416d52e6133a06',
    messagingSenderId: '629488447603',
    projectId: 'zoomy-clone',
    storageBucket: 'zoomy-clone.appspot.com',
    iosClientId: '629488447603-m8mvfode7r0jua7e6aosle8pr8s08dla.apps.googleusercontent.com',
    iosBundleId: 'Maheresio.zoomyClone.RunnerTests',
  );
}
